AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Member

Resources:
  MyMemberS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  MemberLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      MemorySize: 512
#      Handler: gx.Member::handler
#      Handler: gx.HandlerWeatherData
#      Handler: gx.HandlerList
      Handler: gx.S3EventHandler
      CodeUri: target/member.zip
